
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.StringTokenizer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yhy
 */
public class EditStudentRequest extends javax.swing.JFrame {

    /**
     * Creates new form EditStudentRequest
     */
    public EditStudentRequest() {
        initComponents();
        
        grade.removeAllItems();
        grade.addItem("1");
        grade.addItem("2");
        grade.addItem("3");
        grade.addItem("4");
        grade.addItem("5");
        grade.addItem("6");
        grade.addItem("7");
        grade.addItem("8");
        grade.addItem("9");
        grade.addItem("10");
        grade.addItem("11");
        grade.addItem("12");
        
        
        help.removeAllItems();
        help.addItem("Select subject");
        help.addItem("English");
        help.addItem("Maths");
        help.addItem("Science");
        help.addItem("Computer science");
        help.addItem("Music");
        help.addItem("Social studies");
        help.addItem("Visual art");
        help.addItem("PE");
        
        
        
        
        
        
        
        //below is the code to initialize student name combobox
        id.removeAllItems();
        id.addItem("Select student");
        try
        {
            FileReader read = new FileReader("New.txt");
            BufferedReader rr = new BufferedReader(read);
            
            String curr = "";
            
            while((curr=rr.readLine())!=null)
            {
                StringTokenizer tok = new StringTokenizer(curr, ",");
                
                String idn = tok.nextToken();
                String na = tok.nextToken();
                
                String grade = tok.nextToken();
                
                String help = tok.nextToken();
                
                
                id.addItem(idn+","+na);
            }
            rr.close();
        }
        catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        id = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        help = new javax.swing.JComboBox<>();
        grade = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Edit student info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Grade level");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Subject that need help with");

        id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jButton3.setText("Remove this student");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        help.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        grade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Select student");

        jLabel4.setText("Email address");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Edit student request module");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel6))
                                    .addGap(121, 121, 121)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(grade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(help, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Homepage h = new Homepage();
        h.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //this button to edit student info
        int error = 0;
        //completeness check
        
        
        if((grade.getSelectedItem()+"").equals("Select grade"))
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select a grade level.", "Message: error!", javax.swing.JOptionPane.ERROR_MESSAGE);
            error++;
        }
        if((help.getSelectedItem()+"").equals("Select subject"))
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select a subject.", "Message: error!", javax.swing.JOptionPane.ERROR_MESSAGE);
            error++;
        }
        //completeness check done
        
        
        
        if(error==0)
        {
        
        try
        {
            String idna = id.getSelectedItem()+"";
            
            int gr = Integer.parseInt(grade.getSelectedItem()+"");
            
            String he = help.getSelectedItem()+"";
            
            
            
            //below is the code to access txt and put into an arraylist
            ArrayList<String> newstu = new ArrayList<String>();
            
            FileReader st = new FileReader("New.txt");
            BufferedReader stst = new BufferedReader(st);
            
            String temp = "";
            
            while((temp=stst.readLine())!=null)
            {
                newstu.add(temp);
            }//arraylist completed
            stst.close();
            
            
            
            //initialize filewriter and clear txt
            FileWriter n = new FileWriter("New.txt", false);
            PrintWriter nn = new PrintWriter(n);
            
            
            
            //below to refill txt
            for(int count = 0; count<newstu.size(); count++)
            {
                String info = newstu.get(count);
                
                StringTokenizer tok = new StringTokenizer(info, ",");
                
                String idn = tok.nextToken();
                String name = tok.nextToken();
                String em = tok.nextToken();
                String grade = tok.nextToken();
                
                String help = tok.nextToken();
                
                if(idna.equals(idn+","+name))
                {
                    nn.println(idna+","+email.getText()+","+gr+","+he);
                }
                else
                {
                    nn.println(info);
                }
            }
            //txt refilled
            nn.close();
            
            javax.swing.JOptionPane.showMessageDialog(null, "New student added!", "Message: successful!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e)
        {
            
        }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        //this button to remove student
        try
        {
            String idna = id.getSelectedItem()+"";
            
            
            //below is the code to access txt and put into an arraylist
            ArrayList<String> newstu = new ArrayList<String>();
            
            FileReader st = new FileReader("New.txt");
            BufferedReader stst = new BufferedReader(st);
            
            String temp = "";
            
            while((temp=stst.readLine())!=null)
            {
                newstu.add(temp);
            }//arraylist completed
            stst.close();
            
            
            
            //initialize filewriter and clear txt
            FileWriter n = new FileWriter("New.txt", false);
            PrintWriter nn = new PrintWriter(n);
            
            
            
            //below to refill txt
            for(int count = 0; count<newstu.size(); count++)
            {
                String info = newstu.get(count);
                
                StringTokenizer tok = new StringTokenizer(info, ",");
                
                String id = tok.nextToken();
                String name = tok.nextToken();
                String ema = tok.nextToken();
                String grade = tok.nextToken();
                String help = tok.nextToken();
                
                
                if(idna.equals(id+","+name))
                {
                    
                }
                else
                {
                    nn.println(info);
                }
            }
            //txt refilled
            nn.close();
            
            javax.swing.JOptionPane.showMessageDialog(null, "Student removed!", "Message: successful!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e)
        {
            
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed

        String idn = id.getSelectedItem()+"";
        
        try
        {
            
            //below to read volunteer txt
            FileReader readSR = new FileReader("New.txt");
            BufferedReader SR = new BufferedReader(readSR);
            
            String temp = "";
            
            while((temp=SR.readLine())!=null)
            {
                StringTokenizer tok = new StringTokenizer(temp, ",");
                
                String id = tok.nextToken();
                String na = tok.nextToken();
                String em = tok.nextToken();
                String gr = tok.nextToken();
                String he = tok.nextToken();
                

                if((id+","+na).equals(idn))
                {
                    email.setText(em);
                    grade.setSelectedItem(gr);
                    help.setSelectedItem(he);
                    
                }
            }//finish reading volunteer txt
            SR.close();
        }
        catch(Exception e)
        {
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStudentRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStudentRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStudentRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStudentRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStudentRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> grade;
    private javax.swing.JComboBox<String> help;
    private javax.swing.JComboBox<String> id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
