
import static java.awt.AWTEventMulticaster.add;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.StringTokenizer;
import static jdk.vm.ci.sparc.SPARC.l2;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yhy
 */
public class EditVisitorRequest extends javax.swing.JFrame {

    /**
     * Creates new form EditParentRequest
     */
    public EditVisitorRequest() {
        initComponents();
        
        period.removeAllItems();
        period.addItem("Select");
        period.addItem("8:00 am to 9:20 am");
        period.addItem("9:30 am to 10:50 am");
        period.addItem("12:10 pm to 13:30 pm");
        period.addItem("13:40 pm tp 15:00 pm");
        
        
        
        l1.removeAllItems();
        l1.addItem("Select");
        l1.addItem("English");
        l1.addItem("Spanish");
        l1.addItem("Chinese");
        l1.addItem("Japanese");
        l1.addItem("Korean");
        l1.addItem("Malay");
        
        sdate.setMinSelectableDate(new Date());
        
        //below to additem names
        name.removeAllItems();
        name.addItem("Select visitor name");
        try
        {
            FileReader read = new FileReader("Visitor.txt");
            BufferedReader rr = new BufferedReader(read);
            
            String curr = "";
            
            while((curr=rr.readLine())!=null)
            {
                StringTokenizer tok = new StringTokenizer(curr, ",");
                
                String na = tok.nextToken();
                String p = tok.nextToken();
                String em = tok.nextToken();
                String da = tok.nextToken();
                String per = tok.nextToken();
                String lang = tok.nextToken();
                
                
                name.addItem(na);
            }
            rr.close();
        }
        catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        l1 = new javax.swing.JComboBox<>();
        period = new javax.swing.JComboBox<>();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        sdate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Edit visitor application");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Remove this application");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Phone number");

        jLabel4.setText("Date & Time period");

        jLabel5.setText("Language you prefer to speak");

        l1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        period.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        period.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodActionPerformed(evt);
            }
        });

        jLabel1.setText("Visitor name");

        jLabel2.setText("Email");

        name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setText("Edit visitor request module");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(l1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnum)
                                    .addComponent(email)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(sdate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(period, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel6)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(period, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(sdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Homepage h = new Homepage();
        h.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int error = 0;
        //completeness check
        
        if(pnum.getText().equals(""))
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Please input visitor phone number.", "Message: error!", javax.swing.JOptionPane.ERROR_MESSAGE);
            error++;
        }
        if(email.getText().equals(""))
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Please input visitor email address.", "Message: error!", javax.swing.JOptionPane.ERROR_MESSAGE);
            error++;
        }
        if(sdate.getDate()==null)
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Please input date of the visit.", "Message: error!", javax.swing.JOptionPane.ERROR_MESSAGE);
            error++;
        }
        if((period.getSelectedItem()+"").equals("Select"))
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select time period of the visit.", "Message: error!", javax.swing.JOptionPane.ERROR_MESSAGE);
            error++;
        }
        if((l1.getSelectedItem()+"").equals("Select"))
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Please input preferred language of visitor.", "Message: error!", javax.swing.JOptionPane.ERROR_MESSAGE);
            error++;
        }
        
        //validity check
        SimpleDateFormat df = new SimpleDateFormat("EEEE");
        String day = df.format(sdate.getDate());
        if(day.equals("Saturday") || day.equals("Sunday"))
        {
            javax.swing.JOptionPane.showMessageDialog(null, "School opens only on weekdays. Please select a week day to visit", "Message: error!", javax.swing.JOptionPane.ERROR_MESSAGE);
            error++;
        }
        
        if(error==0)
        {
        //edit parent application
        try
        {
            String na = name.getSelectedItem()+"";
            String phone = pnum.getText();
            String em = email.getText();
            
            Date t = sdate.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String d = sdf.format(t);
            
            String per = period.getSelectedItem()+"";
            
            String lang = l1.getSelectedItem()+"";
            
            
            
            
            //below is the code to access txt and put into an arraylist
            ArrayList<String> getinfo = new ArrayList<String>();
            
            FileReader ne = new FileReader("Visitor.txt");
            BufferedReader nee = new BufferedReader(ne);
            
            String curr = "";
            
            while((curr=nee.readLine())!=null)
            {
                getinfo.add(curr);
            }//arraylist filled
            nee.close();
            
            
            
            //initialize filewriter and clear txt
            FileWriter p = new FileWriter("Visitor.txt", false);
            PrintWriter pp = new PrintWriter(p);
            
            
            //below to refill text
            for(int count = 0; count < getinfo.size(); count++)
            {
                String info = getinfo.get(count);
                
                StringTokenizer tok = new StringTokenizer(info, ",");
                
                String name = tok.nextToken();
                String num = tok.nextToken();
                String ema = tok.nextToken();
                String dat = tok.nextToken();
                String period = tok.nextToken();
                String language = tok.nextToken();
                
                
                if(name.equals(na) && phone.equals(num) || ema.equals(em))
                {
                    pp.println(na+","+phone+","+em+","+d+","+per+","+lang);
                }
                else
                {
                    pp.println(info);
                }
            }
            //txt refilled
            
            pp.close();
            
            javax.swing.JOptionPane.showMessageDialog(null, "Visitor application modified!", "Message: successful!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e)
        {
            
        }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        //remove application
        try
        {
            String na = name.getSelectedItem()+"";
            
            
            //below is the code to access txt and put into an arraylist
            ArrayList<String> getinfo = new ArrayList<String>();
            
            FileReader ne = new FileReader("Visitor.txt");
            BufferedReader nee = new BufferedReader(ne);
            
            String curr = "";
            
            while((curr=nee.readLine())!=null)
            {
                getinfo.add(curr);
            }//arraylist filled
            nee.close();
            
            
            
            //initialize filewriter and clear txt
            FileWriter p = new FileWriter("Visitor.txt", false);
            PrintWriter pp = new PrintWriter(p);
            
            
            //below to refill text
            for(int count = 0; count < getinfo.size(); count++)
            {
                String info = getinfo.get(count);
                
                StringTokenizer tok = new StringTokenizer(info, ",");
                
                String name = tok.nextToken();
                String num = tok.nextToken();
                String em = tok.nextToken();
                String dat = tok.nextToken();
                String per = tok.nextToken();
                String lang = tok.nextToken();
                
                if(name.equals(na))
                {
                    
                }
                else
                {
                    pp.println(info);
                }
            }
            //txt refilled
            
            pp.close();
            
            javax.swing.JOptionPane.showMessageDialog(null, "Visitor application removed!", "Message: successful!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void periodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed

        //read visitor info
        String n = name.getSelectedItem()+"";
        try
        {
            FileReader read = new FileReader("Visitor.txt");
            BufferedReader rr = new BufferedReader(read);
            
            String curr = "";
            
            while((curr=rr.readLine())!=null)
            {
                StringTokenizer tok = new StringTokenizer(curr, ",");
                
                String na = tok.nextToken();
                String num = tok.nextToken();
                String em = tok.nextToken();
                String dat = tok.nextToken();
                String per = tok.nextToken();
                String lang = tok.nextToken();
                
                
                if(na.equals(n))
                {
                    pnum.setText(num);
                    email.setText(em);
                    period.setSelectedItem(per);
                    
                    l1.setSelectedItem(lang);
                    
                    java.util.Date date2 = new SimpleDateFormat("dd/MM/yyyy").parse(dat);
                    sdate.setDate(date2);
                    
                }
            }
            rr.close();
        }
        catch(Exception e)
        {
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditVisitorRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditVisitorRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditVisitorRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditVisitorRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditVisitorRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> l1;
    private javax.swing.JComboBox<String> name;
    private javax.swing.JComboBox<String> period;
    private javax.swing.JTextField pnum;
    private com.toedter.calendar.JDateChooser sdate;
    // End of variables declaration//GEN-END:variables
}
